version: '2'
services:
  apic-rdbms:
    image: sysco/apim-mysql:2.1.0
    environment:
        MYSQL_ROOT_PASSWORD: root
    ports:
    - "3306:3306"
  analytics:
    image: sysco/apim-analytics:2.1.0
    environment:
      - SLEEP=100
    ports:
    - "9448:9444"
  traffic-manager:
    image: sysco/apim-traffic-manager:2.1.0
    environment:
      - SLEEP=0
    ports:
    - "9447:9443"
  keymanager:
    image: sysco/apim-keymanager:2.1.0
    environment:
      - SLEEP=110
    ports:
    - "9443:9443"
  gateway-manager:
    image: sysco/apim-gateway-manager:2.1.0
    environment:
      - SLEEP=150
    ports:
    - "9444:9443"
  gateway-worker:
    image: sysco/apim-gateway-worker:2.1.0
    environment:
      - SLEEP=230
    ports:
    - "8280:8280"
    - "8243:8243"
    links:
      - gateway-manager
  store:
    image: sysco/apim-store:2.1.0
    environment:
      - SLEEP=250
    ports:
    - "9446:9443"
  publisher:
    image: sysco/apim-publisher:2.1.0
    environment:
      - SLEEP=200
    ports:
      - "9445:9443"
