analytics:
  image: sysco/apic-analytics:{VERSION}
  ports:
    - "9448:9444"
    - "7712:7712"
  extra_hosts:
    - "apic-rdbms:{RDBMS_IP}"
  labels:
      io.rancher.scheduler.affinity:host_label: service=analytics
      io.rancher.container.pull_image: always
traffic-manager:
  image: sysco/apic-traffic-manager:{VERSION}
  ports:
    - "9447:9443"
  extra_hosts:
    - "apic-rdbms:{RDBMS_IP}"
  links:
    - analytics
  labels:
      io.rancher.scheduler.affinity:host_label: service=trafficmanager
      io.rancher.container.pull_image: always
keymanager:
  image: sysco/apic-keymanager:{VERSION}
  ports:
    - "9443:9443"
  extra_hosts:
    - "apic-rdbms:{RDBMS_IP}"
    - "keymanager:127.0.0.1"
  links:
    - analytics
  environment:
    - SLEEP=60
  labels:
      io.rancher.scheduler.affinity:host_label: service=keymanager
      io.rancher.container.pull_image: always
gateway-manager:
  image: sysco/apic-gateway-manager:{VERSION}
  ports:
    - "9444:9443"
  extra_hosts:
    - "apic-rdbms:{RDBMS_IP}"
    - "gateway-manager:127.0.0.1"
  links:
    - analytics
  environment:
    - SLEEP=100
  labels:
      io.rancher.scheduler.affinity:host_label: service=manager
      io.rancher.container.pull_image: always
gateway-worker:
  image: sysco/apic-gateway-worker:{VERSION}
  ports:
    - "8280:8280"
    - "8243:8243"
  links:
    - gateway-manager
    - traffic-manager
    - analytics
    - keymanager
  extra_hosts:
    - "apic-rdbms:{RDBMS_IP}"
    - "gateway-worker:127:0.0.1"
  environment:
    - SLEEP=180
  labels:
      io.rancher.scheduler.affinity:host_label: service=gateway
      io.rancher.container.pull_image: always
store:
  image: sysco/apic-store:{VERSION}
  ports:
    - "9446:9443"
  extra_hosts:
    - "apic-rdbms:{RDBMS_IP}"
    - "store:127.0.0.1"
  links:
    - analytics
    - keymanager
  environment:
    - SLEEP=200
  labels:
      io.rancher.scheduler.affinity:host_label: service=store
      io.rancher.container.pull_image: always
publisher:
  image: sysco/apic-publisher:{VERSION}
  ports:
    - "9445:9443"
  extra_hosts:
    - "apic-rdbms:{RDBMS_IP}"
    - "publisher:127.0.0.1"
  links:
    - keymanager
    - gateway-manager
    - analytics
  environment:
    - SLEEP=150
  labels:
      io.rancher.scheduler.affinity:host_label: service=publisher
      io.rancher.container.pull_image: always
